apiVersion: v1
kind: Service
metadata:
  name: spid-testenv-identityserver
  labels:
    app: spid-ids
spec:
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: 30280
  selector:
    app: spid-ids
    tier: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spid-ids
  labels:
    app: spid-ids
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spid-ids
        tier: backend
    spec:
      containers:
      - image: italia/spid-testenv-identityserver:docker-compose
        name: spid-ids
        ports:
        - containerPort: 9443
          name: spid-ids